spring:
  application:
    name: eureka
server:
  port: 8889
eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/