#端口号
server:
  port: 8882
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: hello-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8888/eureka/