#端口号
server:
  port: 8881
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: hello-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true

eureka:
  #客户端
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/