server:
  port: 7993
spring:
  application:
    name: stream-consumer2
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        input:
          destination: stream-demo