spring:
  application:
    name: zuul
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
zuul:
  routes:
    hello-service:
      path: /hello-service/**
      serviceId: hello-service
    feign-client:
      path: /feign-client/**
      serviceId: feign-client