server:
  port: 7777
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leiqjl/config-repo-demo.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
